# Generated by Django 3.2 on 2021-06-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0003_auto_20210605_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
