# Generated by Django 3.2 on 2021-06-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0005_auto_20210626_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='genre_name',
            new_name='price',
        ),
    ]
