# Generated by Django 3.2 on 2021-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0006_rename_genre_name_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempo',
            name='tempo',
            field=models.CharField(max_length=50),
        ),
    ]
