# Generated by Django 3.2 on 2021-06-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0007_alter_tempo_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
