# Generated by Django 3.2 on 2021-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0008_auto_20210626_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='tempo',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Tempo',
        ),
    ]
