# Generated by Django 3.2 on 2021-06-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0010_auto_20210626_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
