# Generated by Django 3.2 on 2021-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0012_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='beat',
            name='tempo',
        ),
    ]
