# Generated by Django 3.2 on 2021-06-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0013_auto_20210626_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='tempo',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='meowapp.tempo'),
        ),
    ]
