# Generated by Django 3.2 on 2021-06-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0014_beat_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='tempo',
            field=models.ForeignKey(default=140, on_delete=django.db.models.deletion.CASCADE, to='meowapp.tempo'),
        ),
    ]
