# Generated by Django 3.2 on 2021-06-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0015_alter_beat_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='tempo',
        ),
        migrations.DeleteModel(
            name='Tempo',
        ),
    ]
