# Generated by Django 3.2 on 2021-06-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0016_auto_20210626_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='beat',
            name='tempo',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='meowapp.tempo'),
        ),
    ]
