# Generated by Django 3.2 on 2021-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0018_beat_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='beat',
            name='tempo',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Tempo',
        ),
    ]
