# Generated by Django 3.2 on 2021-06-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0019_auto_20210628_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meowapp.key'),
        ),
    ]
