# Generated by Django 3.2 on 2021-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0020_alter_beat_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='price',
            field=models.FloatField(),
        ),
    ]
