# Generated by Django 3.2.8 on 2021-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowapp', '0021_alter_beat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='duration',
            field=models.DurationField(max_length=5),
        ),
    ]
